config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  

from lib.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('recipe/', include("recipe.urls")),
    
    path('comment/', include("comment.urls", namespace="comment")),
    path('staffroom/', include("staffroom.urls", namespace="staffroom")),
    path('login', LoginView.as_view(template_name="login.html"), name="login"), 
    path('logout', LogoutView.as_view(template_name="logout.html"), name="logout"), 


    
    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

recipe/urls.py
from django.urls import path

from recipe.views import RecipeDetailView, RecipeListView 

app_name = "recipe"

urlpatterns = [
    path('', RecipeListView.as_view(), name="index"),
    path('<int:pk>', RecipeDetailView.as_view(), name="detail"),
]

src/python/comment/urls.py
from django.urls import path

from comment.views import comment_create

app_name = "comment"

urlpatterns = [
    path('create', comment_create, name="create"),
]

src/python/config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.conf import settings  
from django.conf.urls.static import static  

from lib.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('recipe/', include("recipe.urls", namespace="recipe")),
    
    path('comment/', include("comment.urls", namespace="comment")),
    path('staffroom/', include("staffroom.urls", namespace="staffroom")), 
    path('login', LoginView.as_view(template_name="login.html"), name="login"), 
    path('logout', LogoutView.as_view(template_name="logout.html"), name="logout"),


    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/python/recipe/urls.py
from django.urls import path

from recipe.views import RecipeDetailView, RecipeListView  


app_name = "recipe"

urlpatterns = [
    path('', RecipeListView.as_view(), name="index"),

    path('<int:pk>', RecipeDetailView.as_view(), name="detail"),
]

comment/models.py
from django.db import models
from recipe.models import Recipe

# Create your models here.
class Comment(models.Model):

    content = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, default=None, null=True)  # === 追加 ===

recipe/models.py
from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# Create your models here.
class Recipe(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=200)
    content = models.TextField(verbose_name="内容")
    description = models.TextField(blank=True,default="")
    
    image = models.ImageField(upload_to="images/uploaded/", default=None, null=True, blank=True)

    detail_main = ImageSpecField(
        source="image",
        processors=[ResizeToFill(640, 480)],
        format="jpeg",
        options={"quality": 80}
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)


    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        verbose_name = "レシピ"
        verbose_name_plural = "レシピ"
        
    def __str__(self):
        return self.title

src/python/recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField 
from imagekit.processors import ResizeToFill 

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=200)
    content = models.TextField(verbose_name="内容")

    description = models.TextField(blank=True, default="") 

    image = models.ImageField(upload_to="images/uploaded/", default=None, null=True, blank=True)

    detail_main = ImageSpecField(
        source="image",
        processors=[ResizeToFill(640, 480)],
        format="jpeg",
        options={"quality": 80}
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)


    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "レシピ"
        verbose_name_plural = "レシピ"
        
    def __str__(self):
        return self.title

recipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ["title", "content", "description", "image", "user", ]
        widgets = {
            "user": forms.HiddenInput()
        }

src/python/recipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ["title", "content", "description", "image", "user", ]

        widgets = {
            "user": forms.HiddenInput()
        }

recipe/views.py
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView,
    DeleteView
)
from .models import Recipe
from comment.forms import CommentForm
from django.urls import reverse
from django.urls import reverse, reverse_lazy
from django.contrib import messages


class RecipeListView(ListView):
    model = Recipe
    
    def get_queryset(self):
        qs = Recipe.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
            qs = qs.filter(title__contains=keyword)

        return qs

class RecipeCreateView(CreateView):
    model = Recipe
    fields = ["title", "content", "description", "image", ]
    success_url = reverse_lazy("recipe:index")
    
    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "保存できませんでした")
        return super().form_invalid(form)
    
class RecipeDetailView(DetailView):
    model = Recipe
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['CommentForm'] = CommentForm(initial={'recipe': self.object})

        return context
    
class RecipeUpdateView(UpdateView):
    model = Recipe
    fields = ["title", "content", "description", "image", ]
    
    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("recipe:detail",kwargs={"pk":pk})
    
    def form_valid(self,form):
        messages.success(self.request,"更新しました")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)
        
class RecipeDeleteView(DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipe:index")
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました")
        return super().delete(request, *args, **kwargs)

src/python/recipe/views.py
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView,
    DeleteView
)
from .models import Recipe
from comment.forms import CommentForm
from django.urls import reverse
from django.urls import reverse, reverse_lazy
from django.contrib import messages

class RecipeListView(ListView):
    model = Recipe
    
    def get_queryset(self):
        qs = Recipe.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
            qs = qs.filter(title__contains=keyword)

        return qs


class RecipeCreateView(CreateView):
    model = Recipe
    fields = ["title", "content", "description", "image", ]
    success_url = reverse_lazy("recipe:index")
    
    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "保存できませんでした")
        return super().form_invalid(form)

class RecipeDetailView(DetailView):
    model = Recipe
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['CommentForm'] = CommentForm(initial={'recipe': self.object})

        return context


class RecipeUpdateView(UpdateView):
    model = Recipe
    fields = ["title", "content", "description", "image", ]
    success_url = "/"
    
    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("recipe:detail", kwargs={"pk": pk})
    
    def form_valid(self, form):
        messages.success(self.request, "更新しました")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)
    
class RecipeDeleteView(DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipe:index")
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました")
        return super().delete(request, *args, **kwargs)

recipe/templates/recipe/recipe_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %} 


{% block body %}

    <div class="row my-3">
        <div class="col-lg-12">
            <h1>{{ recipe.title }}</h1>
        </div>
        <div class="col-lg-7">
            {% if recipe.image %}
            <img src="{{ recipe.detail_main.url }}" width="640" class="img-fluid rounded border">
            {% else %}
            <img src="{% static 'images/01.jpg' %}" width="640" class="img-fluid rounded border">
        {% endif %}        </div>
        <div class="col-lg-5">
            <h3>作り方</h3>
            <p>{{ recipe.content }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3>このレシピの説明</h3>
            <p>{{ recipe.description }}</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <p class="text-muted">投稿日：{{ recipe.created }}</p>
        </div>
        <div class="col">
            <p class="text-muted">変更日：{{ recipe.modified }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3>コメント</h3>
            <ul class="list-unstyled">
                {% for comment in recipe.comment_set.all %}
                    <li class="border-bottom mt-2">
                        {{ comment.content }} -- ({{ comment.created }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" action="{% url 'comment:create' %}">
                {% csrf_token %}
                {{ CommentForm }}
                <button type="submit" class="btn btn-primary">送信</button>
            </form>
        </div>
    </div>
    {% if request.user.is_authenticated and request.user == recipe.user %}
    <hr>
<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-info" href="{% url 'staffroom:recipe:update' recipe.id %}">編集</a>
        <a class="btn btn-danger" href="{% url 'staffroom:recipe:delete' recipe.id %}">削除</a>
    </div>
</div>
    {% endif %}


{% endblock %}

recipe/templates/recipe/recipe_list.html
{% extends "base.html" %}
{% load static %}
{% load imagekit %}

{% block body %}

    <h1>レシピ一覧</h1>

    {% for recipe in recipe_list %}

    <div class="media">
        {% if recipe.image %}
        {% thumbnail "120x90" recipe.image -- class="align-self-center mr-3" %}
    {% else %}
        <img src="{% static 'images/01.jpg' %}"
            class="align-self-center mr-3" alt="..." width="120">
    {% endif %}        <div class="media-body">
            <a href="{% url 'recipe:detail' recipe.id %}">
            <h5 class="mt-0">{{ recipe.title }}</h5>
        </a>
            <p>{{recipe.description}}</p>

        </div>
    </div>

    {% if not forloop.last %}
    <hr>
    {% endif %}

    {% endfor %}

{% endblock %}