config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  

from lib.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('recipe/', include("recipe.urls")),
    
    path('comment/', include("comment.urls", namespace="comment")),
    path('staffroom/', include("staffroom.urls", namespace="staffroom")),
    path('login', LoginView.as_view(template_name="login.html"), name="login"), 
    path('logout', LogoutView.as_view(template_name="logout.html"), name="logout"), 


    
    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

recipe/urls.py
from django.urls import path

from recipe.views import RecipeDetailView, RecipeListView 

app_name = "recipe"

urlpatterns = [
    path('', RecipeListView.as_view(), name="index"),
    path('<int:pk>', RecipeDetailView.as_view(), name="detail"),
]

src/python/config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.conf import settings  
from django.conf.urls.static import static  

from lib.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('recipe/', include("recipe.urls", namespace="recipe")),
    
    path('comment/', include("comment.urls", namespace="comment")),
    path('staffroom/', include("staffroom.urls", namespace="staffroom")), 
    path('login', LoginView.as_view(template_name="login.html"), name="login"), 
    path('logout', LogoutView.as_view(template_name="logout.html"), name="logout"),


    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

recipe/models.py
from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# Create your models here.
class Recipe(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=200)
    content = models.TextField(verbose_name="内容")
    description = models.TextField(blank=True,default="")
    
    image = models.ImageField(upload_to="images/uploaded/", default=None, null=True, blank=True)

    detail_main = ImageSpecField(
        source="image",
        processors=[ResizeToFill(640, 480)],
        format="jpeg",
        options={"quality": 80}
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)


    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        verbose_name = "レシピ"
        verbose_name_plural = "レシピ"
        
    def __str__(self):
        return self.title

lib/views.py
from django.views.generic import TemplateView
from recipe.models import Recipe

class IndexTemplateView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['recipe_list'] = Recipe.objects.order_by("-created")
        
        try:
            context['recipe_top'] = Recipe.objects.order_by('?')[0]
        except IndexError:
            context['recipe_top'] = None
        
        return context

src/python/lib/views.py
from django.views.generic import TemplateView

from recipe.models import Recipe

class IndexTemplateView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['recipe_list'] = Recipe.objects.order_by("-created")
        
        try:
            context['recipe_top'] = Recipe.objects.order_by('?')[0]
        except IndexError:
            context['recipe_top'] = None
        
        return context

src/python/lib/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>レシピ投稿サイト レシピポスト - Recipe Post</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/small-business.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">レシピポスト</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'recipe:index' %}">レシピ</a>
            </li>
        </ul>
      </div>
      <form class="form-inline">
        <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" type="search" eholder="Search" aria-label="Search"><!--この行を修正-->
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
    </div>
  </nav>

  <!-- Page Content -->
<div class="container">
    {% if messages %}
        {% for message in messages %}

            <div{% if message.tags %} class="my-3 alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"{% endif %} role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

        {% endfor %}
    {% endif %}

    {% block body %}{% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark mt-3">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Recipe Post 2023</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

src/python/lib/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <!-- Heading Row -->
    <div class="row align-items-center my-5">
        <div class="col-lg-7">
            {% if recipe_top.image %}
                <img class="img-fluid rounded mb-4 mb-lg-0" src="{{ recipe_top.image.url }}" alt="">
            {% else %}
                <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'images/01.jpg' %}" alt="">
            {% endif %}
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-5">
            <h1 class="font-weight-light">{{ recipe_top.title }}</h1>
            <p>{{ recipe_top.description }}</p>
            {% if recipe_top %}
            <a class="btn btn-primary" href="{% url 'recipe:detail' recipe_top.id %}">詳細</a>
            {% endif %}
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <!-- Call to Action Well -->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body">
            <p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">
        {% for recipe in recipe_list %}
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    {% if recipe.image %}
                        <img class="card-img-top" src="{{ recipe.image.url }}" alt="{{ recipe.title }}"/>
                    {% else %}
                        <img class="card-img-top" src="{% static 'images/01.jpg' %}" alt="{{ recipe.title }}"/>
                    {% endif %}
                    <div class="card-body">
                        <h2 class="card-title">{{ recipe.title }}</h2>
                        <p class="card-text">{{ recipe.description }}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-primary btn-sm">詳しく見る</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

    <!-- /.row -->

{% endblock %}

src/python/lib/templates/login.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ログイン - Recipe Post</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4">ログイン</h3>
                                    </div>
                                    <div class="card-body">
                                        <form method="post">
                                            {% csrf_token %}
                                            {{ form|crispy }}

                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn btn-primary">ログイン</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

src/python/lib/templates/logout.html
{% extends "base.html" %}

{% block body %}

    <h1>ログアウトしました</h1>

{% endblock %}